import os
import json
from dotenv import load_dotenv
from prompt_builder import build_prompt
from gemini_client import call_gemini

# Load environment variables from .env file
load_dotenv()

# ── Set your Gemini API key here ──────────────────────────────
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY", "YOUR_GEMINI_API_KEY_HERE")
# ─────────────────────────────────────────────────────────────

STAGE2_JSON = r"..\stage2_3\output\stage2_graph.json"
STAGE4_JSON = r"..\stage4\stage4_results.json"
OUTPUT_FILE = "stage5_explanation.txt"


def load_json(path, name):
    if not os.path.exists(path):
        print(f"  ERROR: {name} not found at {path}")
        print(f"  Run the previous stage first.")
        return None
    with open(path, encoding="utf-8") as f:
        return json.load(f)


if __name__ == "__main__":
    print(f"\n{'='*60}")
    print("  STAGE 5 — LLM Explainability (Gemini 2.5 Flash)")
    print(f"{'='*60}\n")

    # Check API key
    if GEMINI_API_KEY == "YOUR_GEMINI_API_KEY_HERE":
        key = input("  Enter your Gemini API key: ").strip()
        if not key:
            print("  ERROR: No API key provided.")
            exit(1)
        GEMINI_API_KEY = key

    # Load stage data
    print("  Loading stage 2 data...")
    stage2 = load_json(STAGE2_JSON, "Stage 2 graph")
    if not stage2: exit(1)

    print("  Loading stage 4 data...")
    stage4 = load_json(STAGE4_JSON, "Stage 4 results")
    if not stage4: exit(1)

    # Merge image_size into summary for prompt builder
    stage2_for_prompt = {
        "summary":    stage2.get("summary", {}),
        "image_size": stage2.get("image_size", {"width": 937, "height": 669}),
    }

    print("  Building prompt...")
    prompt = build_prompt(stage2_for_prompt, stage4)

    print(f"  Prompt length: {len(prompt)} characters")
    print("  Calling Gemini 2.5 Flash...\n")

    # Call Gemini
    explanation = call_gemini(prompt, GEMINI_API_KEY, stream=True)

    # Save output
    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        f.write("STAGE 5 — STRUCTURAL ANALYSIS REPORT\n")
        f.write("Generated by Gemini 2.5 Flash\n")
        f.write("="*60 + "\n\n")
        f.write(explanation)

    print(f"\n{'='*60}")
    print(f"  Explanation saved: {OUTPUT_FILE}")
    print(f"{'='*60}\n")
